### ISSUE TITLE
Lua error on zoning in to Legion raid after r28 update

### ISSUE THREAD

**Issue by TheCheat54** [DeadlyBossMods/DBM-Legion#9]
Updated all the old expansion modules this morning which included the r28 Legion update. Upon zoning in to Antorus on Mythic, I received the following error:

Date: 2022-01-16 08:07:33
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\DBM-AntorusBurningThrone\Eonar.lua line 131:
   attempt to concatenate field 'TOP' (a nil value)
Debug:
   [string "@DBM-AntorusBurningThrone\Eonar.lua"]:131: in main chunk
   [string "=[C]"]: LoadAddOn()
   [string "@DBM-Core\DBM-Core.lua"]:3392: LoadMod()
   [string "@DBM-Core\DBM-Core.lua"]:3335: LoadModsOnDemand()
   [string "@DBM-Core\DBM-Core.lua"]:3273: func()
   [string "@DBM-Core\modules\Scheduler.lua"]:171:
      DBM-Core\modules\Scheduler.lua:162

**Comment by QartemisT** [comment]
Is your DeadlyBossMods up to date (the core)

**Comment by TheCheat54** [comment]
Yes, core updated with the version 9.1.24-24-gbaf622e released 7 hours ago.

**Comment by QartemisT** [comment]
Pushing out a new release now with a bunch of fixes in :)

**Comment by TheCheat54** [comment]
Took the Legion update and reloaded, no error. Thanks!
